name: CI and CD

# trigger the workflow on push
# but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  build and deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
	      with: 
	        node-version: "18.x"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
	      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
