name: CI and CD

# trigger the workflow on push
# but only for the master branch
on:
  push:
    branches:
      - main

jobs:
  build and deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: "18.x"
      - name: Install packages
        run: npm install
      - name: Deploy
        run: npm run deploy